### PR TITLE
Testing/dev/create unit tests

### PR DESCRIPTION
**Pull request by slaee**

### CODE REVIEW

**Comment by omega13-engr** [comment]
All goods, fixed na ang github actions for django CI workflows.

**Comment by omega13-engr** [comment]
@acalys mention unya ko diri if magpa review naka sa unit tests...

**Comment by AlysCarillo** [comment]
> @acalys mention unya ko diri if magpa review naka sa unit tests...

@slaee please niya ko review sly if enough test cases naba na

**Comment by acalys** [comment]
> @acalys mention unya ko diri if magpa review naka sa unit tests...

@slaee please niya ko review if enough test cases na ba na, thanks.

**Pull request merged**
